### ISSUE TITLE
Add way for cli to read config file, either yaml or json

### ISSUE THREAD

**Issue by treeder** [iron-io/iron_worker_ruby_ng#140]
eg usage:

```
iron_worker --config config/config.yml upload my_worker
```

Will read config.yml and look at iron: first, then root for token/project_id. eg config file:

``` yaml
iron:
  token: 'IRON_TOKEN'
  project_id: 'PROJECT_ID'

other:
  stuff:
```
